# Generated by Django 4.2.13 on 2026-10-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiffState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_minute', models.IntegerField()),
                ('backfill_day', models.IntegerField(blank=True, null=True)),
                ('backfill_floor', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SequenceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sequence', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_start', models.IntegerField(blank=True, null=True)),
                ('batch_target', models.IntegerField(blank=True, null=True)),
                ('backfill_sequence', models.IntegerField(blank=True, null=True)),
                ('backfill_floor', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
