# Generated by Django 4.2.13 on 2025-03-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='changesets_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='hashtags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='imagery_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='locale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='remaining_tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='review_requested',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='streetcomplete_quest_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
