# Generated by Django 4.2.13 on 2025-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0002_changeset_changesets_count_changeset_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='created_by_family',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='imagery_used',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
