# Generated by Django 4.2.13 on 2026-03-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0004_sequencestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='imagery_family',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
