# Generated by Django 4.2.13 on 2026-03-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0005_changeset_imagery_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencestate',
            name='batch_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sequencestate',
            name='batch_target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
