# Generated by Django 4.2.13 on 2026-03-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0006_sequencestate_batch_start_sequencestate_batch_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_start', models.IntegerField()),
                ('seq_end', models.IntegerField()),
                ('current_seq', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
