# Generated by Django 4.2.13 on 2026-03-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0007_importjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='locale_family',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
