# Generated by Django 4.2.13 on 2026-09-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0008_changeset_locale_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencestate',
            name='backfill_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sequencestate',
            name='backfill_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
