# Generated by Django 4.2.13 on 2026-09-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0009_sequencestate_backfill_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='created_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='created_by_family',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='imagery_family',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='locale_family',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='user',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
