# Generated by Django 4.2.13 on 2026-09-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0010_alter_changeset_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
                ('count', models.IntegerField()),
                ('changes_sum', models.BigIntegerField()),
            ],
            options={
                'unique_together': {('date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='DailyBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('editor', 'Editor'), ('imagery', 'Imagery'), ('locale', 'Locale'), ('contributor', 'Contributor')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('changes_sum', models.BigIntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'name'], name='changesets__categor_681777_idx')],
                'unique_together': {('date', 'category', 'name')},
            },
        ),
    ]
