# Generated by Django 4.2.13 on 2026-09-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0011_dailyvolume_dailybreakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollupState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='changeset',
            name='user',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
