# Generated by Django 4.2.13 on 2026-09-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0012_rollupstate_alter_changeset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='locale_family',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
