# Generated by Django 4.2.13 on 2026-09-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0013_alter_changeset_locale_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='locale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
