# Generated by Django 4.2.13 on 2026-09-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0016_filtervalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtervalue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
