# Generated by Django 4.2.13 on 2026-09-19 09:39

# Drops the table backing the one-shot HTTP-triggered import feature
# (ChangesetListView/ImportJobView, `/api/sequence/`+`/api/import-job/`),
# removed 2026-09-19 — see CLAUDE.md's "Key entry points" section. Not a
# hypertable, so a plain DeleteModel is correct (no SeparateDatabaseAndState/
# atomic=False needed, unlike changesets_changeset's own migrations).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0038_drop_old_geo_caggs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportJob',
        ),
    ]
