# Generated by Django 4.2.13 on 2026-09-26 00:36

from django.db import migrations, models


# Supports _canonical_values() in views.py: filters resolve a case-insensitive
# input to its exact stored spelling(s) here, then filter the hypertable with
# plain equality, which compressed chunks' bloom-filter sparse indexes can use
# (UPPER(col) = UPPER(x) can't, and decompresses every batch in range).
# - (field, UPPER(value)) index for that lookup (contributor alone is millions
#   of rows at full history).
# - 'language' becomes a FilterValue field (rollups.py now populates it like
#   the others); seeded here from cagg_locale_daily, far cheaper than a
#   DISTINCT over the raw table. '(none)' is the CAgg's NULL bucket, not a value.
# - Country values seeded from country_boundaries (was a separate manual
#   seed_country_filter_values step; load_country_boundaries now does it too,
#   for fresh databases where this runs before the boundaries are loaded).
_CREATE_INDEX_SQL = "CREATE INDEX changesets_filtervalue_field_upper_idx ON changesets_filtervalue (field, upper(value));"
_DROP_INDEX_SQL = "DROP INDEX changesets_filtervalue_field_upper_idx;"

_SEED_SQL = """
INSERT INTO changesets_filtervalue (field, value)
SELECT DISTINCT 'language', name FROM cagg_locale_daily WHERE name <> '(none)'
ON CONFLICT (field, value) DO NOTHING;

INSERT INTO changesets_filtervalue (field, value)
SELECT 'country', TRIM(iso_a2) FROM country_boundaries
ON CONFLICT (field, value) DO NOTHING;
"""
_UNSEED_SQL = "DELETE FROM changesets_filtervalue WHERE field = 'language';"


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0055_centroid_ignore_out_of_range_bbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtervalue',
            name='field',
            field=models.CharField(choices=[('contributor', 'Contributor'), ('editor', 'Editor'), ('imagery', 'Imagery'), ('language', 'Language'), ('country', 'Country')], max_length=20),
        ),
        migrations.RunSQL(sql=_CREATE_INDEX_SQL, reverse_sql=_DROP_INDEX_SQL),
        migrations.RunSQL(sql=_SEED_SQL, reverse_sql=_UNSEED_SQL),
    ]
