# Generated by Django 4.2.13 on 2026-10-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0057_centroid_trigger_from_ingest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiffState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_minute', models.IntegerField()),
                ('backfill_day', models.IntegerField(blank=True, null=True)),
                ('backfill_floor', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
